WIP css修正
natsukikokubu/ts_todo pull request #7
Opened 2023-06-28 13:28 UTC by natsukikokubu

2023-06-29 12:20 UTC, natsukikokubu commented
@tachibanayu24 
一通りの機能は完成しました。レビューをお願いします🙏

2023-06-30 02:56 UTC, tachibanayu24 commented
[add-task #3](https://github.com/natsukikokubu/ts_todo/pull/3)
はこのPRに含まれますかね？
その場合は上記closeしてください

2023-06-30 03:05 UTC, tachibanayu24 requested changes
@natsukikokubu レビューしました。確認お願いします 🙏

2023-06-30 03:05 UTC, tachibanayu24 commented on scripts/main.ts
> +//addTaskという名前の関数を定義し、イベントオブジェクトを引数として受け取る
あと、
```
// addTaskという名前の関数を定義し、イベントオブジェクトを引数として受け取る
```

というコメントは自明すぎるというか、なんの説明もできていません。
この関数がいつ呼び出されて、どのような処理をするのかをサマリーしてください。

2023-06-30 03:05 UTC, tachibanayu24 commented on scripts/main.ts
> +  //フォームの送信イベントのデフォルトの動作をキャンセルすることで、ページがリロードされるnのを防ぐ
```suggestion
  // フォームの送信イベントのデフォルトの動作をキャンセルすることで、ページがリロードされるのを防ぐ
```

2023-06-30 03:05 UTC, tachibanayu24 commented on scripts/main.ts
> +  //指定された各IDを取得
取得するのはIDではなく要素

2023-06-30 03:05 UTC, tachibanayu24 commented on scripts/main.ts
> +  const container = document.getElementById("task-container");
この値はどこからも呼び出されていないようなので不要では
また、task-container自体存在する必要がないように見えるため、idの削除を検討していいかと

2023-06-30 03:05 UTC, tachibanayu24 commented on scripts/main.ts
> +  const taskName = input.value.trim();
👍

2023-06-30 03:05 UTC, tachibanayu24 commented on scripts/main.ts
> +    input.value = "";
[Q]
これはなんのためになにをしているのでしょうか？

2023-06-30 03:05 UTC, tachibanayu24 commented on scripts/main.ts
> +}
この部分は冗長であり不要で、削除しても動きます。そこで、

[Q]
なぜ冗長で、なぜここを消しても動くのでしょうか？

2023-06-30 03:06 UTC, tachibanayu24 commented
コンフリクトの解決もお願いします

2023-07-01 07:51 UTC, natsukikokubu commented on scripts/main.ts
> +}
onsubmit="addTask(event)" が既にフォーム要素に対して直接イベントを設定しているため。

2023-07-01 08:01 UTC, natsukikokubu commented
@tachibanayu24 
修正しましたのでレビューをお願いします！

2023-07-01 09:26 UTC, tachibanayu24 commented on scripts/main.ts
> +}
そのとおりです！

2023-07-01 09:26 UTC, tachibanayu24 commented on scripts/main.ts
> +    input.value = "";
こちらへの回答を。

2023-07-01 09:26 UTC, tachibanayu24 commented on scripts/main.ts
> +  const container = document.getElementById("task-container");
cssを当てていないのであれば、htmlからもid属性を削除していいのでは？

2023-07-01 09:27 UTC, tachibanayu24 commented on scripts/main.ts
> +    //　 チェックボックスにチェックが付いた場合はcompletedListへ移動し
```suggestion
    // チェックボックスにチェックが付いた場合はcompletedListへ移動し
```

2023-07-01 09:28 UTC, tachibanayu24 requested changes
@natsukikokubu 
* PRタイトルの修正
* Qへの回答
* コンフリクトの解決

ができていないようです。もう一度確認お願いします。

2023-07-01 15:34 UTC, merged